### ISSUE TITLE
A user can now see descriptions related to their search queries.

### ISSUE THREAD

**Issue by mstrieleman** [mstrieleman/News-web-app#2]
# Motivation
A user can now view descriptions of articles related to their search query. A card will be generated for each news title & description.

# Implementation 
[1. After retrieving data related to query from newsAPI.org](https://github.com/mstrieleman/News-web-app/issues/1)
2. The app generates a bootstrap card.
3. Article title & description are populated into the cards header and body.
4. The app generates a button within the card & ties it to the url of the original article.
5. The app repeats this process for each result generated (20) & displays them in a descending manner.

# Flow Chart
### State
![state](https://user-images.githubusercontent.com/14259747/40702583-4c7598de-6397-11e8-8acd-7a0d15a8e4c6.PNG)
### Overview
![flowchart](https://user-images.githubusercontent.com/14259747/40702585-4e57b628-6397-11e8-8c00-26f4adb4c123.PNG)
1. Pull articles from https://newsapi.org/
2. Once articles have been retrieved store them in state so we can separate and use the pieces we need for this feature.
3. Use state to populate the cards accordingly

# Wireframe
![wireframe](https://user-images.githubusercontent.com/14259747/40702590-538043c2-6397-11e8-8d5f-fb567481f0e5.PNG)

# Data model
```
author: "Emily Price", 
title: "How to Get iOS 11.4 and Unlock New Messaging and HomePod Features", 
description: "Apple has finally released its much-anticipated pu…a iCloud, stereo pairing for its big HomePod spe…", 
url: "https://lifehacker.com/how-to-get-ios-11-4-and-unlock-new-messaging-and-homepo-1826396464"
```

# Component hierarchy
```
  <Web-App>
      <Fetch API>
          <newsAPI Data/>
      </Fetch API>
  </Web-App>
```

# Research
[Bootstrap Cards](https://getbootstrap.com/docs/4.0/components/card/)

# Tasks
**General** 
- [x]   Create wireframe
- [x]   Create the flowchart
- [x]   Document the data model
- [x]   Document the component hierarchy
- [x]   Generate Bootstrap Card
- [x]   Populate Bootstrap Card header with article title
- [x]   Populate Bootstrap Card body with article description
- [x]   Generate button within card & link button to article url
- [x]   Add slight style for readability
- [x]   (More to come!..?)
