### ISSUE TITLE
A user can now retrieve "breaking" news results from newsAPI.org.

### ISSUE THREAD

**Issue by mstrieleman** [mstrieleman/News-web-app#3]
# Motivation
A user can now check a box to retrieve only the latest "breaking" news articles related to their search.

# Implementation 
1. The app will create a checkbox that when checked will trigger the client to alter the request URL.
2. The new request will return only articles from "top-headlines" section of newsAPI.org
3. [The app places articles in same areas mentioned in issue 2.](https://github.com/mstrieleman/News-web-app/issues/2)

# Flow Chart
![flowchart](https://user-images.githubusercontent.com/14259747/40772910-2c240202-6476-11e8-815d-44ece847fce9.PNG)

# Wireframe
![wireframe](https://user-images.githubusercontent.com/14259747/40772908-2962c238-6476-11e8-91a9-612aec8c9ee9.PNG)

# Data model
```
author: "Emily Price", 
title: "How to Get iOS 11.4 and Unlock New Messaging and HomePod Features", 
description: "Apple has finally released its much-anticipated pu…a iCloud, stereo pairing for its big HomePod spe…", 
URL: "https://lifehacker.com/how-to-get-ios-11-4-and-unlock-new-messaging-and-homepo-1826396464"
```

# Component hierarchy
```
  <Web-App>
      <Fetch API>
          <newsAPI Data/>
      </Fetch API>
  </Web-App>
```

# Research
[news API dot Org! - top headlines section](https://newsapi.org/docs/get-started#top-headlines)

# Tasks
**General** 
- [x]   Create a checkbox below the search field.
- [x]   Label the checkbox so that users know what its for.
- [x]   Link check box to a function: "newsType".
- [x]   Create a new type of state in our search class called: "breaking".
- [x]   Have "newsType" update state of "breaking" to true or false depending on if checked or not.
- [x]   Create if / else if statement within our function that handles search queries.
- If the state of "breaking" is true - alter fetch method to request only breaking news articles.
- If the state of "breaking is false - alter fetch method to request all news articles.
- [x]   More to come!
